server:
  port: 8080
  address: 192.168.200.234
spring:
  application:
    name: ApiGatewayService
  cloud:
    gateway:
      routes:
        - id: IdentityProviderService
          uri: lb://IDENTITYPROVIDERSERVICE
          predicates:
            - Path=/security/**, /users/**

        - id: NetworkService
          uri: lb://NETWORKSERVICE
          predicates:
            - Path=/follows/**,/users/*/follows/**

        - id: ArticleService
          uri: lb://ARTICLESERVICE
          predicates:
            - Path=/articles/**

        - id: TopicService
          uri: lb://TOPICSERVICE
          predicates:
            - Path=/topics/**

        - id: CommentService
          uri: lb://COMMENTSERVICE
          predicates:
            - Path=/comments/**

        - id: ReactionService
          uri: lb://REACTIONSERVICE
          predicates:
            - Path=/reactions/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
