server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: commentModule
          uri: http://localhost:8081/
          predicates:
            - Path=/api/comments/**

        - id: reactModule
          uri: http://localhost:8082/
          predicates:
            - Path=/api/reacts/**
